FROM node:24-alpine AS build
WORKDIR /app
COPY /app-frontend/package*.json ./
RUN npm install
COPY app-frontend .
RUN npm run build


FROM nginx:stable-alpine    
COPY --from=build /app/dist /usr/share/nginx/html
COPY deploy/nginx/nginx.conf /etc/nginx/nginx.conf
# COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]